In [1]:
import os

In [2]:
os.chdir("C:\\Users\\User\\Desktop\\DataSets")

In [3]:
os.chdir("C:/Users/User/Desktop/DataSets")

In [4]:
wd = os.getcwd()

In [6]:
print(wd)

C:\Users\User\Desktop\DataSets


In [7]:
ls

 Volume in drive C is WIN 7
 Volume Serial Number is F836-E034

 Directory of C:\Users\User\Desktop\DataSets

22-Apr-18  08:23 AM    <DIR>          .
22-Apr-18  08:23 AM    <DIR>          ..
22-Apr-18  08:16 AM             5,155 BikeData.csv
22-Apr-18  08:16 AM            90,167 sampledata2.csv
22-Apr-18  08:16 AM            24,864 StudentSurvey.csv
               3 File(s)        120,186 bytes
               2 Dir(s)  212,105,838,592 bytes free


In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [10]:
bikeData = pd.read_csv("BikeData.csv")

In [11]:
bikeData.head()

user_id  age gender  student  employed                cyc_freq  distance  \
0        1   28      M        1         1                   Daily      3.25   
1        2   35      M        0         1                   Daily      1.11   
2        3   28      M        0         1                   Daily      5.59   
3        4   44      F        0         1  Less than once a month      3.24   
4        5   42      M        0         1  Several times per week       NaN   

   time  speed  
0  15.0  13.00  
1   5.0  13.32  
2  23.0    NaN  
3  24.0   8.10  
4  26.0  18.02

In [12]:
bikeData.head(10)

user_id  age gender  student  employed                 cyc_freq  distance  \
0        1   28      M        1         1                    Daily      3.25   
1        2   35      M        0         1                    Daily      1.11   
2        3   28      M        0         1                    Daily      5.59   
3        4   44      F        0         1   Less than once a month      3.24   
4        5   42      M        0         1   Several times per week       NaN   
5        6   36      M        0         1   Several times per week      3.00   
6        7   45      M        0         1   Several times per week     13.03   
7        8   54      M        0         1   Several times per week      6.21   
8        9   39      M        0         1   Several times per week     13.95   
9       10   44      M        0         0  Several times per month      7.40   

   time  speed  
0  15.0  13.00  
1   5.0  13.32  
2  23.0    NaN  
3  24.0   8.10  
4  26.0  18.02  
5  20.0   9.00  
6  51.0  15.33  
7  39.0   9.55  
8  50.0  16.74  
9  44.0  10.09

In [13]:
bikeData.shape

(121, 9)

In [15]:
bikeData.shape[0]

121

In [16]:
bikeData.dtypes

user_id       int64
age           int64
gender       object
student       int64
employed      int64
cyc_freq     object
distance    float64
time        float64
speed       float64
dtype: object

In [20]:
bikeData = bikeData.rename(columns={'user_id' : 'UserId'})

In [21]:
print(bikeData)

     UserId  age gender  student  employed                 cyc_freq  distance  \
0         1   28      M        1         1                    Daily      3.25   
1         2   35      M        0         1                    Daily      1.11   
2         3   28      M        0         1                    Daily      5.59   
3         4   44      F        0         1   Less than once a month      3.24   
4         5   42      M        0         1   Several times per week       NaN   
5         6   36      M        0         1   Several times per week      3.00   
6         7   45      M        0         1   Several times per week     13.03   
7         8   54      M        0         1   Several times per week      6.21   
8         9   39      M        0         1   Several times per week     13.95   
9        10   44      M        0         0  Several times per month      7.40   
10       11   29      M        0         1                    Daily      4.36   
11       12   32      M     

In [40]:
mobileData = pd.read_csv("MobileData2204.csv")

In [30]:
mobileData.shape

(10, 6)

In [59]:
mobileData.dtypes
mobileData=mobileData[['Name','Gender','Color','Age','Salary','PurchaseFlag']]

In [60]:
x = mobileData.iloc[:,:-1].values

In [35]:
test = [1,2,4,6,8,10]

In [36]:
test

[1, 2, 4, 6, 8, 10]

In [37]:
test[1:4]

[2, 4, 6]

In [38]:
test[-1]

10

In [61]:
print(x)

[['Anusha ' 'F' 'White' 23 25000.0]
 ['Anvesh' 'M' 'Black' 22 nan]
 ['Shreshta' 'F' nan 24 20000.0]
 ['Mounika' 'F' 'White' 25 30000.0]
 ['Pragna' 'F' nan 23 35000.0]
 ['Sindhu' 'F' nan 24 nan]
 ['Tapaswi' 'F' 'Black' 25 29000.0]
 ['Iqra' 'F' nan 25 nan]
 ['Nandish' 'M' nan 21 22000.0]
 ['Govardhan' 'M' 'White' 22 nan]]


In [62]:
x

array([['Anusha ', 'F', 'White', 23, 25000.0],
       ['Anvesh', 'M', 'Black', 22, nan],
       ['Shreshta', 'F', nan, 24, 20000.0],
       ['Mounika', 'F', 'White', 25, 30000.0],
       ['Pragna', 'F', nan, 23, 35000.0],
       ['Sindhu', 'F', nan, 24, nan],
       ['Tapaswi', 'F', 'Black', 25, 29000.0],
       ['Iqra', 'F', nan, 25, nan],
       ['Nandish', 'M', nan, 21, 22000.0],
       ['Govardhan', 'M', 'White', 22, nan]], dtype=object)

In [99]:
y  = mobileData.iloc[:,-1].values

In [100]:
y

array(['Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes'], dtype=object)

In [48]:
from sklearn.preprocessing import Imputer

In [51]:
?Imputer

In [69]:
imp = Imputer(missing_values='NaN', strategy='mean', axis=0)

In [70]:
imp = imp.fit(x[:,3:5])

In [72]:
x[:,3:5] = imp.transform(x[:,3:5])

In [73]:
x

array([['Anusha ', 'F', 'White', 23.0, 25000.0],
       ['Anvesh', 'M', 'Black', 22.0, 26833.333333333332],
       ['Shreshta', 'F', nan, 24.0, 20000.0],
       ['Mounika', 'F', 'White', 25.0, 30000.0],
       ['Pragna', 'F', nan, 23.0, 35000.0],
       ['Sindhu', 'F', nan, 24.0, 26833.333333333332],
       ['Tapaswi', 'F', 'Black', 25.0, 29000.0],
       ['Iqra', 'F', nan, 25.0, 26833.333333333332],
       ['Nandish', 'M', nan, 21.0, 22000.0],
       ['Govardhan', 'M', 'White', 22.0, 26833.333333333332]], dtype=object)

In [74]:
mobileData.head()

Name Gender  Color  Age   Salary PurchaseFlag
0   Anusha       F  White   23  25000.0          Yes
1    Anvesh      M  Black   22      NaN           No
2  Shreshta      F    NaN   24  20000.0          Yes
3   Mounika      F  White   25  30000.0          Yes
4    Pragna      F    NaN   23  35000.0           No

In [75]:
from sklearn.preprocessing import LabelEncoder

In [76]:
?LabelEncoder

In [77]:
x

array([['Anusha ', 'F', 'White', 23.0, 25000.0],
       ['Anvesh', 'M', 'Black', 22.0, 26833.333333333332],
       ['Shreshta', 'F', nan, 24.0, 20000.0],
       ['Mounika', 'F', 'White', 25.0, 30000.0],
       ['Pragna', 'F', nan, 23.0, 35000.0],
       ['Sindhu', 'F', nan, 24.0, 26833.333333333332],
       ['Tapaswi', 'F', 'Black', 25.0, 29000.0],
       ['Iqra', 'F', nan, 25.0, 26833.333333333332],
       ['Nandish', 'M', nan, 21.0, 22000.0],
       ['Govardhan', 'M', 'White', 22.0, 26833.333333333332]], dtype=object)

In [78]:
labelEnc = LabelEncoder()

In [79]:
x[:,0] = labelEnc.fit_transform(x[:,0])

In [80]:
x

array([[0, 'F', 'White', 23.0, 25000.0],
       [1, 'M', 'Black', 22.0, 26833.333333333332],
       [7, 'F', nan, 24.0, 20000.0],
       [4, 'F', 'White', 25.0, 30000.0],
       [6, 'F', nan, 23.0, 35000.0],
       [8, 'F', nan, 24.0, 26833.333333333332],
       [9, 'F', 'Black', 25.0, 29000.0],
       [3, 'F', nan, 25.0, 26833.333333333332],
       [5, 'M', nan, 21.0, 22000.0],
       [2, 'M', 'White', 22.0, 26833.333333333332]], dtype=object)

In [82]:
x[:,1] = labelEnc.fit_transform(x[:,1])

In [84]:
x

array([[0, 0, 'White', 23.0, 25000.0],
       [1, 1, 'Black', 22.0, 26833.333333333332],
       [7, 0, nan, 24.0, 20000.0],
       [4, 0, 'White', 25.0, 30000.0],
       [6, 0, nan, 23.0, 35000.0],
       [8, 0, nan, 24.0, 26833.333333333332],
       [9, 0, 'Black', 25.0, 29000.0],
       [3, 0, nan, 25.0, 26833.333333333332],
       [5, 1, nan, 21.0, 22000.0],
       [2, 1, 'White', 22.0, 26833.333333333332]], dtype=object)

In [92]:
from sklearn.cross_validation import train_test_split

In [87]:
!pip install scikit-learn

You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [94]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20)

In [93]:
?train_test_split

In [95]:
x_train

array([[9, 0, 'Black', 25.0, 29000.0],
       [3, 0, nan, 25.0, 26833.333333333332],
       [6, 0, nan, 23.0, 35000.0],
       [1, 1, 'Black', 22.0, 26833.333333333332],
       [4, 0, 'White', 25.0, 30000.0],
       [2, 1, 'White', 22.0, 26833.333333333332],
       [8, 0, nan, 24.0, 26833.333333333332],
       [5, 1, nan, 21.0, 22000.0]], dtype=object)

In [101]:
y_train

array([[  2.50000000e+01,   2.90000000e+04],
       [  2.50000000e+01,              nan],
       [  2.30000000e+01,   3.50000000e+04],
       [  2.20000000e+01,              nan],
       [  2.50000000e+01,   3.00000000e+04],
       [  2.20000000e+01,              nan],
       [  2.40000000e+01,              nan],
       [  2.10000000e+01,   2.20000000e+04]])

In [97]:
x_test

array([[7, 0, nan, 24.0, 20000.0],
       [0, 0, 'White', 23.0, 25000.0]], dtype=object)

In [98]:
y_test

array([[  2.40000000e+01,   2.00000000e+04],
       [  2.30000000e+01,   2.50000000e+04]])

In [102]:
y

array(['Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes'], dtype=object)